# Generated by Django 3.1.5 on 2021-01-15 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Доступ в админку')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': '1. Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'организацию',
                'verbose_name_plural': '2. Организации',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('status', models.CharField(choices=[('Работает', 'Работает'), ('Не работает', 'Не работает'), ('В отпуске', 'В отпуске')], max_length=150, verbose_name='Статус в организации')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'сотрудника',
                'verbose_name_plural': '5. Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_from', models.DateTimeField(verbose_name='Дата/время начала работы')),
                ('ended_at', models.DateTimeField(verbose_name='Дата/время окончания работы')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='core.organization', verbose_name='Организация')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='core.person')),
            ],
            options={
                'verbose_name': 'рабочее время',
                'verbose_name_plural': '6. Рабочее время',
            },
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_places', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'рабочее место',
                'verbose_name_plural': '3. Рабочие места',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.organization', verbose_name='Организация')),
                ('work_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.workplace', verbose_name='Рабочее место')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': '4. Должность',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='core.post', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='core.workplace', verbose_name='Рабочее место'),
        ),
    ]
